### ISSUE TITLE
Configure datasources

### ISSUE THREAD

**Issue by Andrewsh86** [FollettSchoolSolutions/perfmon4j-reports#64]
The user should be able to create, edit, and delete datasources.
Datasources should be tied to the user who created them.
The datasources that are options on the create/edit chart screen should pull from the current user's datasources.
The option to create, edit, delete datasources is on the chart create/edit screen.
Charts should map to datasources by ID.

**Comment by RRobey** [comment]
This is 99% done.  There are a few "nice to have" issues that are labeled as enchancements.  This branch is ready to be merged, but should be reviewed before a merge is made.

**Comment by Andrewsh86** [comment]
datasources aren't created on the edit/create chart screeen.  there was technical difficulty in doing this because of angular.  In the interest of getting to MVP, we put this on the home screen.

**Comment by ddeuchert** [comment]
The current implementation only accepts a host name. It should accept a protocol, host, port and optionally a root path:

For example instead of entering 172.16.16.64 for MDAPP datasource you would be required to enter:
http://172.16.16.64/

This allow you to specify an https connection: https://172.16.16.64/ 
or select an alternate port: http://172.16.16.64:8080

You should also be able to optionally specify a root path. This will be use full if a proxy is placed in front of the datasource. For example a follett hosted datasource might be located at:
https://follettsoftware.com/perfmon4j/datasources

**Comment by pizzaboy314** [comment]
so we should have:    
- a dropdown for http vs https and tack that on in front of the host ip?   
- a host ip field   
- an optional port field?   
- a path field for adding after the host ip?

**Comment by ddeuchert** [comment]
No.  We can have a single field.  The user can be expected to enter a full path.  We should one or more examples:

Like: For example to connect to a datasource on your local machine enter:

http://localhost:8080/

**Comment by pizzaboy314** [comment]
so just provide examples of what you can enter?

**Comment by RRobey** [comment]
The data source object is being appended to a pre defined string, "http://"+
datasource+"/perfmon.." All you really need to do is remove the hard coded
string in the code, and have the user input the entire url into the add
data source textbox. Think the connection string gets built in charts. This
should have been done from the start, but Daniel and I overlooked it

**Comment by pizzaboy314** [comment]
I agree with Robert. I think you should be able to enter almost anything, since the host field is just a string and the API connection string is just built in charts by tacking the parameters after the host field. Am I wrong?
