### ISSUE TITLE
Change table name for DataSource

### ISSUE THREAD

**Issue by RRobey** [FollettSchoolSolutions/perfmon4j-reports#75]
DataSource table should be renamed to DataSources.

**Comment by pizzaboy314** [comment]
@ddeuchert @Andrewsh86 @Rayfucious what is the JBoss / Hibernate standard on this?

**Comment by Rayfucious** [comment]
I don’t think hibernate can help you here.  In the relational database world this would require a migration strategy, something that I think perfmon4j-reports has been able to avoid thus far.

A manual approach would be to login to the mysql admin and do this by hand during the upgrade process.  Preferably we would have a process in place to support this in a clean way however.

Why do we want to change the table name?

**Comment by pizzaboy314** [comment]
@Rayfucious maybe my question was unclear. I'm aware that renaming the database table would have effects, though not really, since we've changed the entire schema and have to start over next deploy anyways.

My actual question: what is the JBoss / Hibernate standard on **table naming**?
**IE _plural_ vs _singular_**

**Comment by Rayfucious** [comment]
Since I like to use the same name for my tables that I use for the entities that map them, when dealing with hibernate, I most often favor “singular” forms except where expressing them in a plural form would make sense

You will find that convention varies by application and technology involved.  At Follett we have used both singular and plural forms for our tables for both good and bad reasons.  One way to look at the question is how it looks in a typical expression of the involved language.

For example this reads funny.
Users user = new Users(userName, password)
em.persist(user);

**Comment by pizzaboy314** [comment]
I agree. Closing this.
