### ISSUE TITLE
Save/Update messages for DataSources / Test Connection Dialog

### ISSUE THREAD

**Issue by RRobey** [FollettSchoolSolutions/perfmon4j-reports#77]
We did not implement "save successful/save fail" messages for save/updateing a datasource.  This would be a nice thing to have.

**Comment by Andrewsh86** [comment]
When updating a datasource, clicking update also does not close the popup.

**Comment by ddeuchert** [comment]
The current implementation only accepts a host name.  It should accept a protocol, host, port and optionally a root path:

For example instead of entering 172.16.16.64 for MDAPP datasource you would be required to enter:
http://172.16.16.64/ 

This allow you to specify an https connection:  https://172.16.16.64/ 
or select an alternate port:  http://172.16.16.64:8080

You should also be able to optionally specify a root path.  This will be use full if a proxy is placed in front of the datasource.  For example a follett hosted datasource might be located at:
     https://follettsoftware.com/perfmon4j/datasources

**Comment by pizzaboy314** [comment]
"When updating a datasource, clicking update also does not close the popup."
This has been fixed/adjusted.

**Comment by pizzaboy314** [comment]
@ddeuchert 
Do we want to have popup messages for confirmation of saving/updating datasources?

**Comment by pizzaboy314** [comment]
@ddeuchert says this is not needed, as we have test connection.
